export const ControlPointAction = {
  ROTATE: 'ROTATE',
  RESIZE_TOP: 'RESIZE_TOP',
  RESIZE_TOP_RIGHT: 'RESIZE_TOP_RIGHT',
  RESIZE_RIGHT: 'RESIZE_RIGHT',
  RESIZE_BOTTOM_RIGHT: 'RESIZE_BOTTOM_RIGHT',
  RESIZE_BOTTOM: 'RESIZE_BOTTOM',
  RESIZE_BOTTOM_LEFT: 'RESIZE_BOTTOM_LEFT',
  RESIZE_LEFT: 'RESIZE_LEFT',
  RESIZE_TOP_LEFT: 'RESIZE_TOP_LEFT',
} as const;

export type ControlPointActionType = keyof typeof ControlPointAction;
